Support failover for postgres

diff --git a/ansible/roles/postgres/database/templates/promote-to-master.sh.j2 b/ansible/roles/postgres/database/templates/promote-to-master.sh.j2
--- a/ansible/roles/postgres/database/templates/promote-to-master.sh.j2
+++ b/ansible/roles/postgres/database/templates/promote-to-master.sh.j2
@@ -1,12 +1,14 @@
 #!/bin/bash
 set -e
 
+# Khai báo đường dẫn đầy đủ từ Ansible
+PG_BIN_DIR="{{ '/usr/pgsql-' + postgres_version + '/bin' if is_redhat_based else '/usr/lib/postgresql/' + postgres_version + '/bin' }}"
+PGDATA="{{ postgres_data_dir }}"
+
 echo "Promoting standby to master..."
-pg_ctl promote -D {{ postgres_data_dir }}
-
-echo "Waiting for promotion to complete..."
-while [ ! -f {{ postgres_data_dir }}/recovery.done ]; do
-  sleep 1
-done
-
-echo "Promotion complete. Node is now master."
+if [ -f "$PG_BIN_DIR/pg_ctl" ]; then
+    $PG_BIN_DIR/pg_ctl -D $PGDATA promote
+else
+    echo "Error: pg_ctl not found in $PG_BIN_DIR"
+    exit 1
+fi
